---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: opendistro-kibana
spec:
  ports:
  - port: 5601
  selector:
    component: opendistro-kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: opendistro-kibana
  name: odfe-kibana
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      component: opendistro-kibana
  template:
    metadata:
      labels:
        component: opendistro-kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: http://opendistro-elasticsearch:9200
        name: opendistro-kibana
        image: amazon/opendistro-for-elasticsearch-kibana:0.8.0
        readinessProbe:
          failureThreshold: 10
          tcpSocket:
            port: 5601
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        livenessProbe:
          failureThreshold: 10
          tcpSocket:
            port: 5601
          initialDelaySeconds: 1
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
        ports:
        - containerPort: 5601
          name: http
          protocol: TCP
